### PR TITLE
Fix and additions to clean up the issues page

### LINKED ISSUE #157: Support for LibsDisguises
Could we get support for disguising entities with LibsDisguises?

https://www.spigotmc.org/resources/libs-disguises.32453/

There could be a command like `disguise [<dEntity to disguise>] [<Disguise Type>] (Disguise options)`

Tags could be like `<e@entity.disguise>` to get the disguise of an entity if the entity is disguised and `<e@entity.disguise.options>` to get any options applied to a disguise.

An event could be something like `on entity disguised`

Thanks!

### PR DESCRIPTION
**Pull request by Mwthorn**
There are old commits in this pull request so its probably a good idea to squish them. Otherwise I've tested everything added in this pull request and stuff should work from 1.8 to 1.12

Features:
Ignore mechanism #185 
Self arguement #187 
PlotSquared clear event

Also someone should close #157

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
You might want to fix this a bit, rather than asking repo maintainer to squash it for you lol

**Comment by Mwthorn** [comment]
Yeah, I tried it a few times and ended up with repeated commits. One day I might get it right

**Comment by Mwthorn** [comment]
Added commits for #159 and #186

File: bukkit/src/main/java/com/denizenscript/depenizen/bukkit/events/towny/PlayerEntersTownScriptEvent.java [hunk 1]
```diff
@@ -99,14 +99,6 @@ public dObject getContext(String name) {
 
     @EventHandler
     public void onTownyPlayerEntersTown(PlayerChangePlotEvent event) {
-        try {
-            if (!event.getTo().getTownyWorld().isUsingTowny() || new ChunkNotification(event.getFrom(), event.getTo()).getNotificationString() == null) {
```
Comment (mcmonkey4eva) [inline bukkit/src/main/java/com/denizenscript/depenizen/bukkit/events/towny/PlayerEntersTownScriptEvent.java]:
```
mcmonkey - Today at 6:05 AM
@MwÞom why does your Depenizen commit just remove a group of checks in the towny events?
MwÞom - Today at 6:05 AM
Cause I don't see why its there
mcmonkey - Today at 6:08 AM
@MwÞom you don't just quietly delete stuff if you don't know what it is
```

File: bukkit/src/main/java/com/denizenscript/depenizen/bukkit/objects/luckperms/LuckPermsTrack.java [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+        try {
+            LuckPermsApi api = LuckPerms.getApi();
+            Track track = api.getTrack(string);
+            if (track == null) {
+                return null;
+            }
+            return new LuckPermsTrack(track);
+        }
+        catch (Throwable e) {
+            // Do nothing.
```
Comment (mcmonkey4eva) [inline bukkit/src/main/java/com/denizenscript/depenizen/bukkit/objects/luckperms/LuckPermsTrack.java]: Why!

Comment (Mwthorn) [reply bukkit/src/main/java/com/denizenscript/depenizen/bukkit/objects/luckperms/LuckPermsTrack.java]: image
Is this fine?

Comment (mcmonkey4eva) [reply bukkit/src/main/java/com/denizenscript/depenizen/bukkit/objects/luckperms/LuckPermsTrack.java]: No. HANDLE THE EXCEPTION. Don't just ignore it.

**Comment by mcmonkey4eva** [comment]
Why is EffectLib support added?

File: bukkit/src/main/java/com/denizenscript/depenizen/bukkit/commands/effectlib/EffectLibCommand.java [hunk 3]
```diff
@@ -0,0 +1,217 @@
...
+        if (duration == null) {
+            dB.echoError(scriptEntry.getResidingQueue(), "Duration not specified!");
+            return;
+        }
+
+        int ticks = duration.getTicksAsInt();
+        Plugin plugin = Support.getPlugin(EffectLibSupport.class);
+        EffectManager effectManager = new EffectManager(plugin);
+
+        // TODO: Find a better way to handle all effects and add custom ones as well
```
Comment (mcmonkey4eva) [inline bukkit/src/main/java/com/denizenscript/depenizen/bukkit/commands/effectlib/EffectLibCommand.java]: This isn't particularly worth having unless/until there's an automated way to trigger any effect type, as mentioned by this TODO line...

Comment (Mwthorn) [reply bukkit/src/main/java/com/denizenscript/depenizen/bukkit/commands/effectlib/EffectLibCommand.java]: There are Configuration-Driven Effects explained on the webpage for EffectLib https://dev.bukkit.org/projects/effectlib
I am not sure how it works, the plugin does not generate any yaml files so I believe this could be done with a new type script if that's possible. Or add something to the config file in Depenizen?

Comment (mcmonkey4eva) [reply bukkit/src/main/java/com/denizenscript/depenizen/bukkit/commands/effectlib/EffectLibCommand.java]: probably have a script type for that I guess

File: README.md [hunk 4]
```diff
@@ -75,7 +79,9 @@ Supported Plugins: (And the sources we acquired Jar files from.)
 - TerrainControl (https://www.spigotmc.org/resources/terraincontrol.2214/)
 - Towny (http://towny.palmergames.com/)
 - TownyChat (http://towny.palmergames.com/)
+- Vampire (https://www.spigotmc.org/resources/vampire.1906/)
 - Vault (http://dev.bukkit.org/bukkit-plugins/vault/)
+- Vehicles (https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/)
```
Comment (mcmonkey4eva) [inline README.md]: No premium plugin links

**Comment by Mwthorn** [comment]
This pull request is pretty much done now. I have been through almost all issues and got nothing else on my local.

**Comment by mcmonkey4eva** [comment]
There's a lot of real commits in this, but there's also a lot of broken commits in this.
The way it stands, this is best autosquashed to a single commit when pulled (to clear away the broken commits)... but then there's going to be a lot of legit new things all in one commit.
Think you can locally rebase away the bad commits and reorganize this into a sane grouping of commits?

**Comment by mcmonkey4eva** [comment]
This is a bit messy but eh... any needed cleaning can be done in followup PR's / commits
